In [1]:
import numpy as np

First we define our activation function and its derivative

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
def sigmoid_der(x):
    return x*(1-x)

The training function

In [4]:
def train_NN(x,y,neurnum):
    weights1 = 2*np.random.random((x.shape[1],neurnum)) - 1
    weights2 = 2*np.random.random((neurnum,1)) - 1

    
    for j in range(60000):
        hidden = sigmoid(np.dot(x,weights1))
        output = sigmoid(np.dot(hidden,weights2))
    
        output_error = y - output
                    
        out_delta = output_error * sigmoid_der(output)
    
        hidden_error = out_delta.dot(weights2.T)
        
        hidden_delta = hidden_error * sigmoid_der(hidden)
    
        weights2 += hidden.T.dot(out_delta)
        weights1 += x.T.dot(hidden_delta)   
        
    return weights1,weights2


And the predict function

In [5]:
def predict(inputvec,weights):
    hidden_val = sigmoid(np.dot(inputvec,weights[0]))
    return sigmoid(np.dot(hidden_val,weights[1]))

Simple test

In [6]:
x = np.array([  [0.2, 0.4, 0.9],
                [0.9, 0.2, 0.6],
                [0.3, 0.8, 0.3],
                [0.4, 0.3, 0.1] ])


y = np.array([[0.2],
              [0.4],
              [0.5],
              [0.5]])

w = train_NN(x,y,3)

In [7]:
w

(array([[-0.19129066,  1.43826996, -0.49899312],
        [-0.83498506,  1.20282709,  0.3786693 ],
        [ 1.38013192, -1.4987037 ,  0.77202754]]), array([[-1.81620312],
        [ 2.12573347],
        [-1.28145119]]))

Test our weights

In [8]:
for i in range(4):
    print(predict(x[i],w))

[0.2]
[0.4]
[0.5]
[0.5]


In [9]:
predict(np.array([0.5,0.7,0.4]),w)

array([0.48602602])

# XOR 

In [10]:
x2 = np.array([ [0, 0, 1],
                [0, 1, 1],
                [1, 0, 1],
                [1, 1, 1] ])

y2 = np.array([[0],
               [1],
               [1],
               [0]])

w = train_NN(x2,y2,2)

In [11]:
w

(array([[-9.84824907, -1.52892404],
        [-9.84842289, -1.52892772],
        [14.63139289,  1.40415097]]), array([[ 16.4437669 ],
        [-25.57174816]]))

In [12]:
for i in range(4):
    print(predict(x2[i],w))

[0.01652354]
[0.98684927]
[0.98684927]
[0.01791712]
